apiVersion: v1
kind: Service
metadata:
  name: dhs
  namespace: dhs
  labels:
    app.kubernetes.io/name: dhs
    team: team5
spec:
  type: NodePort
  selector:
    app: dhs
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30950
